start = root
root = element root {divi}
    divi = element div { day*, mixed{p | intro | story}}
        day = attribute day {text}
        p = element p {mixed{main_title | ch_title | org | roleName}*}
            main_title = element main_title {text}
            ch_title = element ch_title {text}
            org = element org {type* | subtype* | text }
                type = attribute type {text}
                subtype = attribute subtype {text}
            roleName = element roleName {type* | subtype* | text}
        intro = element intro {p_2}
            p_2 = element p {intro_title}
                intro_title = element intro_title {text}
        story = element story {numbr, p_3, text}
            numbr = attribute numbr {text}
            p_3 = element p {ch_title, org, roleName, text}
        