start = root
root = element root {divi+}
    divi = element div { day*, (p | intro | story | text)*}
        day = attribute day {text}
        
p = element p {mixed{main_title | ch_title | org | roleName | 
    story_numbr | faith | person}* | text}
            main_title = element main_title {text}
            ch_title = element ch_title {text}
            org = element org {mixed{type*, subtype*}}
                type = attribute type {text}
                subtype = attribute subtype {text}
            roleName = element roleName {mixed{type*, subtype*}}
        intro = element intro {p_2*}
            p_2 = element p {intro_title*, text}
                intro_title = element intro_title {text}
        story = element story {numbr*, status*, (censorship_note | p_3)*, text}
            numbr = attribute numbr {text}
            censorship_note = element censorship_note {text}
            status = attribute status {text}
            p_3 = element p {mixed{ch_title | org | roleName | story_numbr | faith | person | p_3 | italian | note | song}* | text}
                story_numbr = element story_numbr {text}
                faith = element faith {ref, text}
                    ref = attribute ref {text}
                italian = element italian {text}
                note = element note {text}
                song = element song {text}
        person = element person {
    attribute name { text },
    attribute sex { text },
    (text | p_3)*
}